### ISSUE TITLE
Fatal error on activation - Call to undefined method GF_Phone_Extension::enqueue_scripts() 

### ISSUE THREAD

**Issue by ClearMarble** [ANEX-Agency/gravityforms-phone-extension#1]
Hey, your plugin seems like exactly what I'm looking for right now. However, upon activation I'm getting a site-breaking fatal error: 

` Fatal error: Uncaught Error: Call to undefined method GF_Phone_Extension::enqueue_scripts() in /home/vagrant/Sites/bordergab/public/wp-content/plugins/gravityforms/gravityforms.php on line 4586`

Any idea what's wrong? I'm using the latest version of Gravity Forms and WP.

Screenshot attached (local dev environment):
![gravityforms-phone-extension-error](https://user-images.githubusercontent.com/13680615/30832884-da51d3be-a21a-11e7-9bec-ecce9fafe8bf.png)

**Comment by JoeHana** [comment]
I just installed it on one of my test sites and it works fine for me - altough I have an older version of GF running. And I also run it on one of my client sites together with the latest version of GF - also without any issues. Not sure if this is maybe because you're working locally? Maybe try it on an online webspace? What PHP Version are you using btw?

**Comment by ClearMarble** [comment]
Ah, both my local version and the live site are running PHP 7...kinda slipped my mind to check for PHP 7 compatibility. My guess is that's probably the source of the issue...I'll try it on a PHP 5 instance when I get a chance just to confirm.

**Comment by JoeHana** [comment]
That would be kind of you. At least it will narrow down the issue and makes it easier to fix. If I find some time I'll do it myself.

**Comment by RaulGarciaHerrera** [comment]
Good Morning from Spain, JoeHana ..
I'm having this same issue with my installation, finally did you two find a solution? was it php version related?
It activates fine, but I get blank pages in front end althougt the admin pages are shown right.
Call to undefined method GF_Phone_Extension::enqueue_scripts() in error.log
Thank you very much for the plugin, it seems to be perfect for my needs

**Comment by insight2learn** [comment]
Good Morning JoeHana from London, UK

I too just had this issue, and have debugged the issue.
Gravity forms and the phone extension work fine together, BUT when I install the popup maker extension BANG - get the error.

https://wordpress.org/plugins/popup-maker/

I am running PHP 7.1

would you be able to fix ? (If you can will make a donation :-)

Fatal error: Uncaught Error: Call to undefined method GF_Phone_Extension::enqueue_scripts() in [source_dir]/wp-content/plugins/gravityforms/gravityforms.php:4785 
Stack trace: 

#0 [source_dir]/wp-content/plugins/gravityforms/gravityforms.php(5223): GFForms::enqueue_form_scripts('3', true) 
#1 [source_dir]/wp-content/plugins/popup-maker/includes/integrations/class-pum-gravity-forms.php(43): gravity_form_enqueue_scripts('3', true) 
#2 [source_dir]/wp-includes/class-wp-hook.php(286): PUM_Gravity_Forms_Integation::preload(407) 
#3 [source_dir]/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) 
#4 [source_dir]/wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
#5 [source_dir]/wp-content/plugins/popup-maker/classes/Site/Popups.php(129): do_action('popmake_preload...', 407) 
#6 [source_dir]/wp-content/plugins/gravityforms/gravityforms.php on line 4785

**Comment by JoeHana** [comment]
Unfortunately it is not possible for me to re-produce this error for some reason. However, I took some time to improve the script and styles loading, according to the GravityForms Addon Framework. Not sure if that fixes that issue but perhaps you want to give it a shot and let me know.

**Comment by insight2learn** [comment]
Hi JoeHana, Excellent, that fixed the issue for me many thanks - donation coming your way :-)

**Comment by JoeHana** [comment]
Glad that it works now, thanks for the donation. :)
