### ISSUE TITLE
 separateDialCode: true but  not show the dial code

### ISSUE THREAD

**Issue by tupsky** [ANEX-Agency/gravityforms-phone-extension#2]
i set separateDialCode: true 
but nothing happen the country dial code not showing

**Comment by JoeHana** [comment]
Where did you set that?

**Comment by tupsky** [comment]
intlTelInput.js

**Comment by JoeHana** [comment]
I haven't developed that script. It is just a script which gets used by my plugin. Usually you just enable this plugin and it will transform your GravityForms phone fields automatically like you can see [here](https://www.rubinarealestate.com/en/property/rooftop-apartment-heart-berlin/) for example (form in the sidebar)

**Comment by shreyask15** [comment]
You have to change Setting in Gravity Forms plugins
1 -> Wp-admin/Forms/Settings/ Output Html 5 - Select Yes
It will works !!

**Comment by kartavyaparekh96** [comment]
yeah its work for me. Thank you @shreyask15
