### ISSUE TITLE
Display corresponding country code

### ISSUE THREAD

**Issue by arihant23** [ANEX-Agency/gravityforms-phone-extension#4]
Hi,

Your plugin is just awesome. Wanted to know if there is any way to display the corresponding country code instead of the flag?

Your help is highly appreciated.

Regards

**Comment by JoeHana** [comment]
Thanks a lot, but I'm afraid that this isn't possible right now. Not sure if this can be customized or so but I'm certain there is no easy way right now. Sorry

**Comment by arihant23** [comment]
Solution here : https://github.com/ANEX-Agency/gravityforms-phone-extension/issues/7#issuecomment-416016263
