### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by jaxonrice** [ANEX-Agency/gravityforms-phone-extension#5]
Is there anything I need to do to get the plugin working besides have a "Phone" (advanced) gravity forms field in my form? 

I have a form with the phone field enabled and the addon enabled in my Gravity Forms (by ANEX - 1.2.1 ), but the form still shows the plain phone fields with the international mask. Am I missing something?

Thanks

**Comment by JoeHana** [comment]
Beside the phone field ensure you're enabling HTML5 in the overall form settings

**Comment by jaxonrice** [comment]
That was the answer! Thanks so much for the quick response.
