### ISSUE TITLE
Gravity View Compatible in editing mode

### ISSUE THREAD

**Issue by arihant23** [ANEX-Agency/gravityforms-phone-extension#7]
Add the below code to init.js after line 3 for proper compatibility with Gravity View in editing mode

	if($form.length===0){
	var $form		= $(".gv-edit-entry-wrapper form");
	};

**Comment by JoeHana** [comment]
Feel free to do a PR for that :)

**Comment by arihant23** [comment]
Here's the final version. Sorry not comfortable with PR

`jQuery(document).ready(function($) {
    
	var $form		= $(".gform_wrapper form");
	if($form.length===0){
		var $form		= $(".gv-edit-entry-wrapper form");
	};
    var $field		= $(".gfield input[type=tel]");

	/**
	 * Init International Telephone Field
	 */
	$field.intlTelInput({
// Shows your preferred country at the top
		preferredCountries: [ "in", "us" ],
// Below config displays the country code besides the flag
		separateDialCode: true,
		initialCountry: "auto",
		geoIpLookup: function(callback) {
			$.get('//ipinfo.io', function() {}, "jsonp").always(function(resp) {
				var countryCode = (resp && resp.country) ? resp.country : "";
				callback(countryCode);
			});
		}
	});
	
	/**
	 * Update the hidden input on form submit
	 */
	$form.submit(function() {
		
		$field.each(function (index, value){
			
			$(this).val($(this).intlTelInput("getNumber"));
			
		});	
		
	});
	
});
`
